import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const ctx = await b.newContext({ viewport: { width: 1280, height: 950 }, acceptDownloads: true });
const p = await ctx.newPage();
const errs = []; p.on('pageerror', e => errs.push(e.message.slice(0, 200)));
await p.goto('http://localhost:3400', { waitUntil: 'networkidle' });
await p.click('button:has-text("통계 수집")');
await p.waitForSelector('text=골든', { timeout: 60000 }).catch(() => {});
await p.waitForTimeout(2500);
await p.screenshot({ path: '/tmp/tabs.png', fullPage: true });
const dl = p.waitForEvent('download', { timeout: 90000 });
await p.click('button:has-text("엑셀 다운로드")');
const d = await dl;
const path = '/tmp/out.xlsx';
await d.saveAs(path);
console.log('다운로드:', d.suggestedFilename());
console.log('에러:', errs.length ? errs.slice(0,3) : '없음');
await b.close();
